services:
  # frontend:
  #   container_name: frontend  
  #   build: ./frontend
  #   ports: 
  #     - 80:80
  #   working_dir: /app-frontend
  backend:
    container_name: backend
    build: ./backend
    ports: 
      - 8080:8080
    working_dir: /app-backend
    depends_on:
      - db
  db:
    container_name: database
    image: postgres:17.1-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '5050:5050'
    depends_on:
      - db